# Generated by Django 5.0.1 on 2024-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(default="1990-04-08"),
            preserve_default=False,
        ),
    ]
